CREATE TABLE IF NOT EXISTS team_data (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    deleted_at TIMESTAMP(6),
    memo varchar(255) DEFAULT NULL,
    team_id bigint UNSIGNED DEFAULT NULL,
    user_id bigint UNSIGNED DEFAULT NULL,
    KEY `FK6CTqVcXLFkvsXsY7NywlkPdup` (team_id),
    KEY `FKagsQdXLwpx3lMINNkFTFmp1A9` (user_id),
    CONSTRAINT `FK6CTqVcXLFkvsXsY7NywlkPdup` FOREIGN KEY (team_id) REFERENCES team (`id`),
    CONSTRAINT `FKagsQdXLwpx3lMINNkFTFmp1A9` FOREIGN KEY (user_id) REFERENCES user (`id`)
);